config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'

  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KagerBoxing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <div class='wrapper'>
    <!-- hedder section starts -->
    <header class="header">
      <div class="container">
        <div class="header-inner">
          <%= link_to root_path, class: "logo" do %>
            <%= image_tag 'logo.png', style:"width: 90px; height: auto", alt: 'Logo' %>
          <% end %>
          <nav class="nav">
            <ul class="nav__list">
              <li class="nav__list-item">
                <%= link_to "Home", "#", class: "nav__list-link" %>
              </li>
              <li class="nav__list-item">
                <%= link_to "Zajęcia", "#", class: "nav__list-link" %>
              </li>
              <li class="nav__list-item">
                <%= link_to "Karnety", "#", class: "nav__list-link" %>
              </li>
              <li class="nav__list-item">
                <%= link_to "Kontakt", contact_path, class: "nav__list-link" %>
              </li>
            </ul>           
          </nav>
          <div class="navlink__list_link-login">
            <%= link_to "Zaloguj się", "#" %>
          </div>
        </div>
      </div>  
    </header>
    <!-- Header section ends -->
    <!-- Main section starts -->
    <main class="main">
      <%= yield %>
    </main>
    <!-- Main section ends -->
    <!-- Footer section starts -->
    <footer class="footer">
      <div class="container">
        <div class="footer-inner">
          <nav class="footer-menu">
            <ul class="footer_menu_list">
              <li class="footer__item">
                <p class="footer__menu_title">O nas</p>
              </li>
              <li class="footer__item">
                <%= link_to "O Trenerze", "#", class: 'footer__menu_link' %>
              </li>  
              <li class="footer__item">
                <%= link_to "Nasza misja", "#", class: 'footer__menu_link' %>
              </li>
              <li class="footer__item">
                <%= link_to "Partnerzy", "#", class: 'footer__menu_link' %>
              </li>       
            </ul>
            <ul class="footer_menu_list">
              <li class="footer__item">
                <p class="footer__menu_title">Prywatność</p>
              </li>
              <li class="footer__item">
                <%= link_to "Cookies", "#", class: 'footer__menu_link' %>
              </li>  
              <li class="footer__item">
                <%= link_to "Prawa użytkowników", "#", class: 'footer__menu_link' %>
              </li>
              <li class="footer__item">
                <%= link_to "Polityka prywatności", "#", class: 'footer__menu_link' %>
              </li>       
            </ul>
            <ul class="footer_menu_list">
              <li class="footer__item">
                <p class="footer__menu_title">Kontakt</p>
              </li>
              <li class="app__item">
              <%= link_to root_path, class: 'app_item-link' do %>
                <%= image_tag 'insta.png', class: 'app__item-img', alt: 'Instagram Kontakt' %>
              <% end %>
              </li>
              <li class="app__item">
                <%= link_to root_path, class: 'logo' do %>
                  <%= image_tag 'telegram.svg', class: 'app__item-img', alt: 'Telegram kontakt' %>
                <% end %>
              </li>     
            </ul>
          </nav>
          <div class="footer-text">
              <p> 
              Drodzy użytkownicy! W przypadku jakichkolwiek pytań lub sugestii prosimy o kontakt z nami pod adresem @kagerboxing@gmail.com там. 
              Jesteśmy tu, aby pomóc! Dziękujemy za odwiedzenie naszej strony!
              </p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/pages/_blog.html.erb
<section class="blog">
  <div class="container">
    <div class="blog_all">
      <div class="blog__item">
        <%= image_tag 'blog-1.jpg', class: 'blog__item-img', alt: 'blog page 1' %>
        <h3 class="blog__under_title">
          Tournament Boxing 2025 in Warszaw
        </h3>
        <%= link_to 'more', '#', class: 'blog__item-link' %>
      </div>
      <div class="blog__item">
        <%= image_tag 'blog-2.jpg', class: 'blog__item-img', alt: 'blog page 1' %>
        <h3 class="blog__under_title">
          McGreggor is CAME BACK?
        </h3>
        <%= link_to 'more', '#', class: 'blog__item-link' %>
      </div>
    </div>
    <%= link_to 'SHOW MORE', '#', class: 'showmore__link' %>
  </div>
<section>

app/views/pages/contact.html.erb
<section class ="contacts">
  <div class="container">
    <h1 class="all__contact_title">
      Czekamy na kontakt od ciebie 
    </h1>
    <ul class="contact_list">
      <li class="contact_item__first">
        <div class="contact_items__content">
          <%= image_tag 'telegram.svg', style:"width: 80px; height: 80px", class: 'contacts__item_img', alt: 'Skontaktuj się z nami przez Telegram' %>
          <h3 class=contact__item_title>
            Skontaktuj się z nami przez Telegram
          </h3>
        </div>
      </li>
      <li class="contact_item__second">
        <div class="contact_items__content">
          <%= image_tag 'insta.png', style:"width: 80px; height: 80px", class: 'contacts__item_img', alt: 'Skontaktuj się z nami przez Instagram' %>
          <h3 class=contact__item_title>
            Skontaktuj się z nami przez Instagram
          </h3>
        </div>
      </li>
      <li class="contact_item__third">
        <div class="contact_items__content">
          <%= image_tag 'mailnew.png', style:"width: 80px; height: 80px", class: 'contacts__item_img', alt: 'Skontaktuj się z nami przez Gmail' %>
          <h3 class=contact__item_title>
            Napisz nam na Poczte
          </h3>
        </div>
      </li>
    </ul>
    <%= render 'blog' %>
  </div>
</section>

app/views/pages/main.html.erb
<div class="bgc">
  <section class="first_section">
    <div class="container">
      <h1 class="main_title">
        ZACZNIJ TRENOWAĆ Z NAMI
      </h1>
    </div>
    <div class="container">
      <div class="main_photos">
        <%= image_tag 'photo1.jpg', class: 'main_photo1', alt: 'box page 1' %>
        <%= image_tag 'photo2.jpg', class: 'main_photo2', alt: 'box page 2' %>
      </div>
    </div>  
  </section>
  <section class="container">
    <h1 class="main_title__boxing">
      Co to jest boks klaszyczny i po co mi treningi?
    </h1>
      <div class="about__boxing_all">
        <p class="about_boxing__title">
          I.Czym jest klasyczny boks?
        </p>
        <p class="about_boxing">
          Klasyczny boks to dyscyplina sportowa, w której dwóch zawodników rywalizuje na ringu,
          używając pięści chronionych rękawicami bokserskimi. Walka odbywa się w seriach rund,
          a celem jest zdobycie punktów lub znokautowanie przeciwnika.
        </p>
        <p class="about_boxing__title">
          II.Dlaczego boks pomaga poprawić kondycję fizyczną?
        </p>
        <p class="about_boxing">
          Boks angażuje wiele grup mięśniowych i znacząco poprawia ogólną kondycję fizyczną.
          Intensywne treningi cardio, siłowe i wytrzymałościowe pomagają spalić kalorie,
          wzmocnić mięśnie i poprawić wydolność organizmu.
        </p>
        <p class="about_boxing__title">
          III.W jaki sposób boks wpływa na rozwój umiejętności samoobrony?
        </p>
        <p class="about_boxing">
          Trening bokserski uczy technik obronnych, zwiększa refleks i szybkość reakcji,
          co może być przydatne w sytuacjach wymagających samoobrony.
          Uczestnicy uczą się, jak unikać ciosów oraz jak skutecznie bronić się przed zagrożeniem.
        </p>
        <p class="about_boxing__title">
          IV.Czy boks może pomóc w radzeniu sobie ze stresem?
        </p>
        <p class="about_boxing">
          Tak, boks jest doskonałym sposobem na rozładowanie napięcia i stresu.
          Intensywny trening pozwala na wyrzucenie negatywnej energii,
          a jednocześnie skupienie się na technikach i strategii pomaga oderwać się od codziennych problemów.
        </p>
        <p class="about_boxing__title">
          V.Jak boks wpływa na rozwój dyscypliny i samodyscypliny?
        </p>
        <p class="about_boxing">
          Regularne treningi bokserskie uczą dyscypliny i samodyscypliny.
          Zawodnicy muszą być konsekwentni w swoich działaniach, zarówno podczas treningów,
          jak i w diecie oraz odpoczynku, aby osiągnąć postępy i sukcesy w tym sporcie.
        </p>
        <p class="about_boxing__title">
          VI.Czy boks rozwija pewność siebie?
        </p>
        <p class="about_boxing">
          Boks wzmacnia poczucie pewności siebie, ucząc zawodników,
          jak radzić sobie w trudnych sytuacjach. Regularne treningi i 
          opanowanie nowych umiejętności przyczyniają się do budowania silnej,
          pozytywnej samooceny.
        </p>
      </div>  
  </section>
  <%= render 'blog' %>
</div>  